//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cargo_transportationPIS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GruzzPISEntities : DbContext
    {
        private static GruzzPISEntities _context;

        public static GruzzPISEntities GetContext()
        {
            if (_context == null)
                _context = new GruzzPISEntities();

            return _context;
        }
        public GruzzPISEntities()
            : base("name=GruzzPISEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Заявки> Заявки { get; set; }
        public virtual DbSet<Маршруты> Маршруты { get; set; }
        public virtual DbSet<Платежи> Платежи { get; set; }
        public virtual DbSet<Пользователи> Пользователи { get; set; }
        public virtual DbSet<Роли> Роли { get; set; }
        public virtual DbSet<Статус> Статус { get; set; }
        public virtual DbSet<Транспорт> Транспорт { get; set; }
        public virtual DbSet<Уведомления> Уведомления { get; set; }
    }
}
