//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cargo_transportationPIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заявки
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Заявки()
        {
            this.Маршруты = new HashSet<Маршруты>();
            this.Уведомления = new HashSet<Уведомления>();
        }
    
        public int ID_заявки { get; set; }
        public Nullable<int> ID_клиента { get; set; }
        public Nullable<int> ID_менеджера { get; set; }
        public Nullable<int> ID_статус { get; set; }
        public Nullable<System.DateTime> Дата { get; set; }
        public string Комментарий { get; set; }
        public string Адрес_отправления { get; set; }
        public string Адрес_прибытия { get; set; }
        public string Название_груза { get; set; }
        public Nullable<int> Вес { get; set; }
        public Nullable<int> Количество { get; set; }
    
        public virtual Пользователи Пользователи { get; set; }
        public virtual Пользователи Пользователи1 { get; set; }
        public virtual Статус Статус { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Маршруты> Маршруты { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Уведомления> Уведомления { get; set; }
    }
}
