//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cargo_transportationPIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Маршруты
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Маршруты()
        {
            this.Платежи = new HashSet<Платежи>();
        }
    
        public int ID_маршрута { get; set; }
        public Nullable<int> ID_водителя { get; set; }
        public Nullable<System.DateTime> Дата_отправки { get; set; }
        public Nullable<System.DateTime> Дата_прибытия { get; set; }
        public Nullable<int> ID_транспорта { get; set; }
        public Nullable<int> ID_статус { get; set; }
        public Nullable<int> ID_заявки { get; set; }
        public Nullable<decimal> Стоимость { get; set; }
    
        public virtual Заявки Заявки { get; set; }
        public virtual Пользователи Пользователи { get; set; }
        public virtual Статус Статус { get; set; }
        public virtual Транспорт Транспорт { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Платежи> Платежи { get; set; }
    }
}
