//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cargo_transportationPIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Платежи
    {
        public int ID_Платежа { get; set; }
        public Nullable<int> ID_маршрута { get; set; }
        public Nullable<decimal> Сумма { get; set; }
        public Nullable<System.DateTime> Дата_платежа { get; set; }
        public Nullable<int> ID_статуса { get; set; }
    
        public virtual Маршруты Маршруты { get; set; }
        public virtual Статус Статус { get; set; }
    }
}
