//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cargo_transportationPIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пользователи
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Пользователи()
        {
            this.Заявки = new HashSet<Заявки>();
            this.Заявки1 = new HashSet<Заявки>();
            this.Маршруты = new HashSet<Маршруты>();
            this.Уведомления = new HashSet<Уведомления>();
        }
    
        public int ID_пользователя { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public System.DateTime Дата_рождения { get; set; }
        public int Телефон { get; set; }
        public string Почта { get; set; }
        public int ID_роли { get; set; }
        public byte[] Фото { get; set; }
        public Nullable<decimal> Стаж { get; set; }
        public Nullable<decimal> Зарплата { get; set; }
        public string Паспорт { get; set; }
        public string Логин { get; set; }
        public string Пароль { get; set; }
        public Nullable<bool> Активен { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Заявки> Заявки { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Заявки> Заявки1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Маршруты> Маршруты { get; set; }
        public virtual Роли Роли { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Уведомления> Уведомления { get; set; }
    }
}
