//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cargo_transportationPIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Уведомления
    {
        public int ID_уведомления { get; set; }
        public Nullable<int> ID_пользователя { get; set; }
        public Nullable<int> ID_заявки { get; set; }
        public string Текст { get; set; }
        public Nullable<System.DateTime> Дата_создания { get; set; }
        public Nullable<bool> Прочитано { get; set; }
    
        public virtual Заявки Заявки { get; set; }
        public virtual Пользователи Пользователи { get; set; }
    }
}
